name: 'Visitor Counter'
description: 'Updates visitor count and regenerates SVG badge'
inputs:
  token:
    description: 'GitHub token with repo access'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GITHUB_TOKEN: ${{ inputs.token }}
