name: reusable-visitor-counter
on:
  schedule:
    - cron: '0 0,12 * * *'
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:
    inputs:
      repo:
        required: true
        type: string
      token:
        required: true
        type: string

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set REPO and GITHUB_TOKEN environment variables
        run: |
          if [ "${{ github.event_name }}" = "workflow_call" ]; then
            echo "REPO=${{ inputs.repo }}" >> $GITHUB_ENV
            echo "GITHUB_TOKEN=${{ inputs.token }}" >> $GITHUB_ENV
          else
            echo "REPO=${{ github.repository }}" >> $GITHUB_ENV
            echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
          fi

      - name: Install dependencies
        run: npm install

      - name: Run generate_svg.js
        run: node generate_svg.js

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add count.json visitor.svg
          git commit -m "Update visitor count" || echo "No changes to commit"
          git push
