name: Update Visitor Count

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-visitor-count:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Update visitor count
        run: node update_repo_views_counter.js
        env:
          TRAFFIC_TOKEN: ${{ secrets.TRAFFIC_TOKEN }}
          REPO: ${{ github.repository }}

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create and push changes to a new branch
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH="update-visitor-count-$(date +%s)"
          git checkout -b $BRANCH
          git add -A
          git commit -m "Update visitor count"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
          git push origin $BRANCH

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.create-and-push.outputs.branch }}
          title: "Update visitor count"
          body: "Automated update of visitor count"
          base: main
