name: Update Visitor Count

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch: # Allows manual triggering

jobs:
  update-visitor-count:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Update visitor count
        run: node update_repo_views_counter.js
        env:
          TRAFFIC_TOKEN: ${{ secrets.TRAFFIC_TOKEN }}
          REPO: ${{ github.repository }}

      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Commit changes
        run: |
          git fetch origin
          git checkout -b ${{ github.event.pull_request.head.ref }} origin/${{ github.event.pull_request.head.ref }}
          git add -A
          git commit -m "Fix Markdown syntax issues" || echo "No changes to commit"
          git pull --rebase origin ${{ github.event.pull_request.head.ref }} || echo "No rebase needed"
          git push origin HEAD:${{ github.event.pull_request.head.ref }}
